<a href="https://colab.research.google.com/github/Dheerajnath/NLP_LAB_EXPERIMENTS/blob/main/NLP_EXPT_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import re

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving twitter4000.csv to twitter4000.csv

In [ ]:
data = pd.read_csv('twitter4000.csv')

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4000 entries, 0 to 3999
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   twitts     4000 non-null   object
 1   sentiment  4000 non-null   int64
dtypes: int64(1), object(1)
memory usage: 62.6+ KB

In [ ]:
data.count()

twitts       4000
sentiment    4000
dtype: int64

In [ ]:
data['sentiment'].value_counts()

sentiment
0    2000
1    2000
Name: count, dtype: int64

In [ ]:
data.head()

                                              twitts  sentiment
0  is bored and wants to watch a movie  any sugge...          0
1           back in miami.  waiting to unboard ship           0
2  @misskpey awwww dnt dis brng bak memoriessss, ...          0
3                  ughhh i am so tired  blahhhhhhhhh          0
4  @mandagoforth me bad! It's funny though. Zacha...          0

In [ ]:
pattern = r'\s'
data['twitts'].apply(lambda x: re.sub(pattern, '', x))

0             isboredandwantstowatchamovieanysuggestions?
1                        backinmiami.waitingtounboardship
2       @misskpeyawwwwdntdisbrngbakmemoriessss,IthnkI'...
3                             ughhhiamsotiredblahhhhhhhhh
4       @mandagoforthmebad!It'sfunnythough.ZacharyQuin...
                              ...
3995                                       ijustgraduated
3996                     Templatingworks;itallhastobedone
3997                          mommyjustbroughtmestarbucks
3998        @omareppswatchingyouonaHousere-run...lovinit.
3999    ThanksfortryingtomakemesmileI'llmakeyour18thsp...
Name: twitts, Length: 4000, dtype: object

In [ ]:
pattern = r'\s'
data['char_count']=data['twitts'].apply(lambda x: len(re.sub(pattern, '', x)))
data

                                                 twitts  sentiment  char_count
0     is bored and wants to watch a movie  any sugge...          0          43
1              back in miami.  waiting to unboard ship           0          32
2     @misskpey awwww dnt dis brng bak memoriessss, ...          0          54
3                     ughhh i am so tired  blahhhhhhhhh          0          27
4     @mandagoforth me bad! It's funny though. Zacha...          0         116
...                                                 ...        ...         ...
3995                                  i just graduated           1          14
3996          Templating works; it all has to be done            1          32
3997                   mommy just brought me starbucks           1          27
3998  @omarepps watching you on a House re-run...lov...          1          45
3999  Thanks for trying to make me smile I'll make y...          1          63

[4000 rows x 3 columns]

In [ ]:
pattern = r'[!"#$%&\'()*+,-./:;<=>?@[\]^_`{|}~]'
data['twitts'] = data['twitts'].apply(lambda x: re.sub(pattern, '', x))
data

,twitts,sentiment,char_count,hash_tags_count,mentions
0,isboredandwantstowatchamovieanysuggestions,0,43,0,0
1,backinmiamiwaitingtounboardship,0,32,0,0
2,misskpeyawwwwdntdisbrngbakmemoriessssIthnkImsa...,0,54,0,0
3,ughhhiamsotiredblahhhhhhhhh,0,27,0,0
4,mandagoforthmebadItsfunnythoughZacharyQuintois...,0,116,0,0
...,...,...,...,...,...
3995,ijustgraduated,1,14,0,0
3996,Templatingworksitallhastobedone,1,32,0,0
3997,mommyjustbroughtmestarbucks,1,27,0,0
3998,omareppswatchingyouonaHousererunlovinit,1,45,0,0
3999,ThanksfortryingtomakemesmileIllmakeyour18thspe...,1,63,0,0

In [ ]:
data['hash_tags_count']= data['twitts'].apply(lambda x: len(re.findall(r'#(\w+)', x)))
data.sample(4)

,twitts,sentiment,char_count,hash_tags_count
382,Lifeisconfusing,0,15,0
3040,@MrSkidmoreGoodjobtonightdude...,1,32,0
355,1stdaybacktosklItsveryhotevenmythintightsfeelu...,0,55,0
3547,@kattwilkieThankyouKathybbz!Itfeelsbetteralready,1,48,0

In [ ]:
data['mentions']= data['twitts'].apply(lambda x: len(re.findall(r'#(\w+)', x)))
data.sample(10)

,twitts,sentiment,char_count,hash_tags_count,mentions
3305,@TalktoDianeHiDiane.Thenewsiteandblogswilllaun...,1,112,0,0
2618,@iwantyourjeepwhat'stheprob?gettingsleepy-shou...,1,76,0,0
3575,@kirstiealley:Ooopsthatshouldhavebeen@GrahamNo...,1,77,0,0
2970,@lilxicanitaawwmecheeeyoucanbemyfriend...lol..,1,46,0,0
2281,shameicanhearmyparentstalkingaboutme*smirks*an...,1,101,0,0
2248,OHyayforgottocomebackNowiwatchedtodaythreemovi...,1,107,0,0
3676,Tonightwasagoodnight,1,20,0,0
2454,isimpatientlywaitingforherlittlesistertogethere!,1,48,0,0
95,Ifonlytheyunderstood...,0,23,0,0
724,"Oki'lltrytouploadmypic...hopeitworks,ifnotinee...",0,55,0,0

In [ ]:
data['twitts'].apply(lambda x: len([word for word in x.split()if word.isupper()]))

0       0
1       0
2       0
3       0
4       0
       ..
3995    0
3996    0
3997    0
3998    0
3999    0
Name: twitts, Length: 4000, dtype: int64